"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T09:00:31.064387+00:00

FIXED VERSION — Addresses code review findings:
  1. [FAIL]  ERROR_HANDLING     — Added try/except around all pipeline stages
  2. [WARN]  ROW_COUNT_LOGGING  — Added .count() logging after each transformation
  3. [WARN]  SCHEMA_VALIDATION  — Added schema checks before transformations

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, max, broadcast, when
from pyspark.sql.types import StringType, FloatType, DateType, StructType, StructField
import datetime
import logging
import os

# ── FIX 2: Set up logging for row counts and pipeline events ──
logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("sigma_pipeline")

# ── FIX 3: Expected schemas for validation ──────────────────
EXPECTED_BRONZE_COLUMNS = {"transaction_id", "amount", "status", "merchant_id",
                           "customer_id", "transaction_date", "payment_method"}

EXPECTED_SILVER_COLUMNS = EXPECTED_BRONZE_COLUMNS | {"merchant_name", "category",
                                                      "city", "quality_flag"}


def validate_schema(df, expected_columns, layer_name):
    """FIX 3: Validate DataFrame schema before transformations."""
    actual_columns = set(df.columns)
    missing = expected_columns - actual_columns
    if missing:
        raise ValueError(
            f"[{layer_name}] Schema validation FAILED — missing columns: {missing}. "
            f"Actual columns: {actual_columns}"
        )
    logger.info(f"[{layer_name}] Schema validation PASSED — all {len(expected_columns)} required columns present")


def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV data
    raw_df = spark.read.csv(input_path, header=True, inferSchema=False)

    # FIX 2: Log row count after read
    raw_count = raw_df.count()
    logger.info(f"[Bronze] Read {raw_count} rows from {input_path}")

    # FIX 3: Validate schema before transformations
    validate_schema(raw_df, EXPECTED_BRONZE_COLUMNS, "Bronze-Ingest")

    # Add metadata columns
    raw_df = raw_df.withColumn("ingestion_timestamp", lit(datetime.datetime.now()))
    raw_df = raw_df.withColumn("source_file", lit(input_path))
    raw_df = raw_df.withColumn("pipeline_run_id", lit(run_id))

    # Overwrite the run_date partition so re-running the same day is idempotent.
    raw_df.write.mode("overwrite").parquet(f"{output_path}/load_date={run_date}")
    logger.info(f"[Bronze] Wrote {raw_count} rows to {output_path}/load_date={run_date}")


def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning
    bronze_df = spark.read.parquet(f"{bronze_path}/load_date={run_date}")

    # FIX 2: Log row count after read
    bronze_count = bronze_df.count()
    logger.info(f"[Silver] Read {bronze_count} rows from Bronze layer")

    # Cast columns to correct types
    bronze_df = bronze_df.withColumn("amount", col("amount").cast(FloatType()))
    bronze_df = bronze_df.withColumn("transaction_date", col("transaction_date").cast(DateType()))
    bronze_df = bronze_df.withColumn("customer_id", col("customer_id").cast(StringType()))
    bronze_df = bronze_df.withColumn("merchant_id", col("merchant_id").cast(StringType()))

    # Filter NULL transaction_id and negative amounts
    bronze_df = bronze_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))

    # FIX 2: Log row count after filtering
    after_filter_count = bronze_df.count()
    logger.info(f"[Silver] After NULL/negative filter: {after_filter_count} rows (dropped {bronze_count - after_filter_count})")

    # Deduplicate on transaction_id keeping latest ingestion_timestamp
    bronze_df = bronze_df.withColumn("rank",
                                    when(col("ingestion_timestamp") ==
                                         max("ingestion_timestamp").over(window.partitionBy("transaction_id")), 1).otherwise(0))
    bronze_df = bronze_df.filter(col("rank") == 1).drop("rank")

    # FIX 2: Log row count after dedup
    after_dedup_count = bronze_df.count()
    logger.info(f"[Silver] After deduplication: {after_dedup_count} rows (removed {after_filter_count - after_dedup_count} duplicates)")

    # Read merchants data and broadcast hint, cache merchants
    merchants_df = spark.read.parquet(merchants_path)
    merchants_df = broadcast(merchants_df)
    merchants_df.cache()

    # Join with merchants
    joined_df = bronze_df.join(merchants_df, bronze_df.merchant_id == merchants_df.merchant_id, "left")

    # Add quality_flag column
    joined_df = joined_df.withColumn("quality_flag",
                                     when(col("merchant_id").isNotNull(), "CLEAN").otherwise("UNMATCHED"))

    # FIX 2: Log row count after join
    joined_count = joined_df.count()
    logger.info(f"[Silver] After merchant join: {joined_count} rows")

    # Write to Silver layer partitioned by date
    joined_df.write.mode("overwrite").parquet(f"{output_path}/load_date={run_date}")
    logger.info(f"[Silver] Wrote {joined_count} rows to {output_path}/load_date={run_date}")


def main():
    # Initialize Spark session
    spark = SparkSession.builder.appName("Customer Segmentation Pipeline").getOrCreate()

    # Define paths and run details
    input_path = os.environ["SIGMA_TRANSACTIONS_RAW_PATH"]
    output_bronze_path = os.environ["SIGMA_BRONZE_OUTPUT_PATH"]
    output_silver_path = os.environ["SIGMA_SILVER_OUTPUT_PATH"]
    merchants_path = os.environ["SIGMA_MERCHANTS_DIM_PATH"]
    run_date = datetime.datetime.now().strftime("%Y%m%d")
    run_id = "run_id_12345"

    # FIX 1: Wrap pipeline stages in try/except for error handling
    try:
        logger.info(f"[Pipeline] Starting Bronze ingestion for run_date={run_date}")
        ingest_bronze(spark, input_path, output_bronze_path, run_date, run_id)
        logger.info("[Pipeline] Bronze ingestion completed successfully")
    except Exception as e:
        logger.error(f"[Pipeline] Bronze ingestion FAILED: {e}")
        raise

    try:
        logger.info(f"[Pipeline] Starting Silver transformation for run_date={run_date}")
        transform_silver(spark, output_bronze_path, merchants_path, output_silver_path, run_date)
        logger.info("[Pipeline] Silver transformation completed successfully")
    except Exception as e:
        logger.error(f"[Pipeline] Silver transformation FAILED: {e}")
        raise

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, min, mode, expr, to_date, countDistinct, avg
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, DateType


def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read the Silver layer data
    silver_df = spark.read.parquet(silver_path)

    # FIX 2: Log row count after read
    silver_count = silver_df.count()
    logger.info(f"[Gold-MerchantPerf] Read {silver_count} rows from Silver layer")

    # FIX 3: Validate schema before transformations
    validate_schema(silver_df, {"status", "merchant_id", "merchant_name", "category", "city", "amount"},
                    "Gold-MerchantPerf")

    # Filter for completed transactions
    completed_txns = silver_df.filter(col("status") == "COMPLETED")

    # FIX 2: Log row count after filter
    completed_count = completed_txns.count()
    logger.info(f"[Gold-MerchantPerf] Completed transactions: {completed_count} of {silver_count}")

    # Calculate metrics
    merchant_performance_df = completed_txns.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
        .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(col("status").isin("FAILED")) / count("*") * 100).alias("failure_rate_pct")
        )

    # FIX 2: Log output row count
    output_count = merchant_performance_df.count()
    logger.info(f"[Gold-MerchantPerf] Output: {output_count} merchant-date groups")

    # Write the output
    merchant_performance_df.write.partitionBy("date").mode("overwrite").parquet(output_path)
    logger.info(f"[Gold-MerchantPerf] Wrote {output_count} rows to {output_path}")


def build_customer_ltv(spark, silver_path, output_path):
    # Read the Silver layer data
    silver_df = spark.read.parquet(silver_path)

    # FIX 2: Log row count after read
    silver_count = silver_df.count()
    logger.info(f"[Gold-CustomerLTV] Read {silver_count} rows from Silver layer")

    # FIX 3: Validate schema before transformations
    validate_schema(silver_df, {"status", "customer_id", "amount", "payment_method"},
                    "Gold-CustomerLTV")

    # Filter for completed transactions
    completed_txns = silver_df.filter(col("status") == "COMPLETED")

    # FIX 2: Log row count after filter
    completed_count = completed_txns.count()
    logger.info(f"[Gold-CustomerLTV] Completed transactions: {completed_count} of {silver_count}")

    # Calculate metrics
    customer_ltv_df = completed_txns.groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            avg("amount").alias("avg_txn_value"),
            min("date").alias("first_txn_date"),
            max("date").alias("last_txn_date"),
            mode("payment_method").alias("preferred_payment_method")
        )

    # FIX 2: Log output row count
    output_count = customer_ltv_df.count()
    logger.info(f"[Gold-CustomerLTV] Output: {output_count} customers")

    # Write the output
    customer_ltv_df.write.mode("overwrite").parquet(output_path)
    logger.info(f"[Gold-CustomerLTV] Wrote {output_count} rows to {output_path}")


def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read the Silver layer data
    silver_df = spark.read.parquet(silver_path)

    # FIX 2: Log row count after read
    silver_count = silver_df.count()
    logger.info(f"[Gold-DailySummary] Read {silver_count} rows from Silver layer")

    # FIX 3: Validate schema before transformations
    validate_schema(silver_df, {"status", "customer_id", "merchant_id", "amount"},
                    "Gold-DailySummary")

    # Filter for completed transactions
    completed_txns = silver_df.filter(col("status") == "COMPLETED")

    # FIX 2: Log row count after filter
    completed_count = completed_txns.count()
    logger.info(f"[Gold-DailySummary] Completed transactions: {completed_count} of {silver_count}")

    # Calculate metrics
    daily_summary_df = completed_txns.groupBy("date") \
       .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("total_txns"),
            countDistinct("customer_id").alias("unique_customers"),
            countDistinct("merchant_id").alias("unique_merchants"),
            (count(col("status").isin("FAILED")) / count("*") * 100).alias("failure_rate_pct")
        )

    # FIX 2: Log output row count
    output_count = daily_summary_df.count()
    logger.info(f"[Gold-DailySummary] Output: {output_count} daily summaries")

    # Write the output
    daily_summary_df.write.partitionBy("date").mode("overwrite").parquet(output_path)
    logger.info(f"[Gold-DailySummary] Wrote {output_count} rows to {output_path}")


def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define output paths
    merchant_performance_path = f"{gold_output_dir}/merchant_performance"
    customer_ltv_path = f"{gold_output_dir}/customer_ltv"
    daily_summary_path = f"{gold_output_dir}/daily_summary"

    # FIX 1: Wrap each Gold stage in try/except for error handling
    try:
        logger.info("[Gold] Starting merchant performance aggregation...")
        build_merchant_performance(spark, silver_path, merchant_performance_path, run_date)
        logger.info("[Gold] Merchant performance completed successfully")
    except Exception as e:
        logger.error(f"[Gold] Merchant performance FAILED: {e}")
        raise

    try:
        logger.info("[Gold] Starting customer LTV aggregation...")
        build_customer_ltv(spark, silver_path, customer_ltv_path)
        logger.info("[Gold] Customer LTV completed successfully")
    except Exception as e:
        logger.error(f"[Gold] Customer LTV FAILED: {e}")
        raise

    try:
        logger.info("[Gold] Starting daily summary aggregation...")
        build_daily_summary(spark, silver_path, daily_summary_path, run_date)
        logger.info("[Gold] Daily summary completed successfully")
    except Exception as e:
        logger.error(f"[Gold] Daily summary FAILED: {e}")
        raise

    # Write run metadata
    run_metadata = {
        "run_date": run_date,
        "output_paths": {
            "merchant_performance": merchant_performance_path,
            "customer_ltv": customer_ltv_path,
            "daily_summary": daily_summary_path
        }
    }

    spark.sparkContext.parallelize([run_metadata]) \
        .write.mode("overwrite").json(f"{gold_output_dir}/run_metadata")
    logger.info(f"[Gold] Run metadata saved to {gold_output_dir}/run_metadata")

# Initialize Spark session
spark = SparkSession.builder.appName("Customer Segmentation Refresh").getOrCreate()

# Example usage
silver_path = os.environ["SIGMA_SILVER_INPUT_PATH"]
gold_output_dir = os.environ["SIGMA_GOLD_OUTPUT_DIR"]
run_date = os.environ["SIGMA_RUN_DATE"]

# FIX 1: Wrap top-level Gold execution in try/except
try:
    run_gold(spark, silver_path, gold_output_dir, run_date)
    logger.info("[Pipeline] Gold layer completed successfully")
except Exception as e:
    logger.error(f"[Pipeline] Gold layer FAILED: {e}")
    raise
