"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
Generated: 2026-05-26T09:00:31.064387+00:00

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, lit, max, broadcast, when, avg, countDistinct
from pyspark.sql.window import Window
from pyspark.sql.types import StringType, FloatType, DateType
import datetime
import logging
import os

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("sigma_pipeline")

EXPECTED_TRANSACTION_COLUMNS = {
    "transaction_id",
    "amount",
    "status",
    "merchant_id",
    "customer_id",
    "transaction_date",
    "payment_method",
}


def validate_schema(df, expected_columns, layer_name):
    missing_columns = expected_columns - set(df.columns)
    if missing_columns:
        raise ValueError(f"{layer_name} is missing required columns: {sorted(missing_columns)}")
    logger.info("%s schema validation passed with %d columns", layer_name, len(df.columns))

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV data
    raw_df = spark.read.csv(input_path, header=True, inferSchema=False)
    input_count = raw_df.count()
    logger.info("[Stage: ingest_bronze] input_count: %s rows", f"{input_count:,}")
    validate_schema(raw_df, EXPECTED_TRANSACTION_COLUMNS, "bronze input")
    
    # Add metadata columns
    raw_df = raw_df.withColumn("ingestion_timestamp", lit(datetime.datetime.now()))
    raw_df = raw_df.withColumn("source_file", lit(input_path))
    raw_df = raw_df.withColumn("pipeline_run_id", lit(run_id))
    output_count = raw_df.count()
    logger.info("[Stage: ingest_bronze] output_count: %s rows", f"{output_count:,}")
    
    # Overwrite the run_date partition so re-running the same day is idempotent.
    raw_df.write.mode("overwrite").parquet(f"{output_path}/load_date={run_date}")

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning
    bronze_df = spark.read.parquet(f"{bronze_path}/load_date={run_date}")
    input_count = bronze_df.count()
    logger.info("[Stage: transform_silver] input_count: %s rows", f"{input_count:,}")
    validate_schema(
        bronze_df,
        EXPECTED_TRANSACTION_COLUMNS | {"ingestion_timestamp", "source_file", "pipeline_run_id"},
        "bronze partition",
    )
    
    # Cast columns to correct types
    bronze_df = bronze_df.withColumn("amount", col("amount").cast(FloatType()))
    bronze_df = bronze_df.withColumn("transaction_date", col("transaction_date").cast(DateType()))
    bronze_df = bronze_df.withColumn("customer_id", col("customer_id").cast(StringType()))
    bronze_df = bronze_df.withColumn("merchant_id", col("merchant_id").cast(StringType()))
    
    # Filter NULL transaction_id and negative amounts
    bronze_df = bronze_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))
    after_filter_count = bronze_df.count()
    logger.info("[Stage: transform_silver] after_filter_count: %s rows", f"{after_filter_count:,}")
    
    # Deduplicate on transaction_id keeping latest ingestion_timestamp
    window = Window.partitionBy("transaction_id")
    bronze_df = bronze_df.withColumn("rank",
                                    when(col("ingestion_timestamp") ==
                                         max("ingestion_timestamp").over(window), 1).otherwise(0))
    bronze_df = bronze_df.filter(col("rank") == 1).drop("rank")
    after_dedup_count = bronze_df.count()
    logger.info("[Stage: transform_silver] after_dedup_count: %s rows", f"{after_dedup_count:,}")
    
    # Read merchants data and broadcast hint, cache merchants
    merchants_df = spark.read.parquet(merchants_path)
    merchants_df = broadcast(merchants_df)
    merchants_df.cache()
    
    # Join with merchants
    joined_df = bronze_df.join(merchants_df, bronze_df.merchant_id == merchants_df.merchant_id, "left")
    
    # Add quality_flag column
    joined_df = joined_df.withColumn("quality_flag", 
                                     when(col("merchant_id").isNotNull(), "CLEAN").otherwise("UNMATCHED"))
    output_count = joined_df.count()
    logger.info("[Stage: transform_silver] output_count: %s rows", f"{output_count:,}")
    
    # Write to Silver layer partitioned by date
    joined_df.write.mode("overwrite").parquet(f"{output_path}/load_date={run_date}")

def main():
    # Initialize Spark session
    spark = SparkSession.builder.appName("Customer Segmentation Pipeline").getOrCreate()
    
    # Define paths and run details
    input_path = os.environ["SIGMA_TRANSACTIONS_RAW_PATH"]
    output_bronze_path = os.environ["SIGMA_BRONZE_OUTPUT_PATH"]
    output_silver_path = os.environ["SIGMA_SILVER_OUTPUT_PATH"]
    merchants_path = os.environ["SIGMA_MERCHANTS_DIM_PATH"]
    run_date = datetime.datetime.now().strftime("%Y%m%d")
    run_id = "run_id_12345"
    
    try:
        # Ingest Bronze layer
        ingest_bronze(spark, input_path, output_bronze_path, run_date, run_id)

        # Transform Silver layer
        transform_silver(spark, output_bronze_path, merchants_path, output_silver_path, run_date)
    except Exception:
        logger.exception("Pipeline failed for run_date=%s run_id=%s", run_date, run_id)
        raise

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
from pyspark.sql.functions import col, sum, count, max, min, mode, expr, to_date
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, DateType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read the Silver layer data
    silver_df = spark.read.parquet(silver_path)
    input_count = silver_df.count()
    logger.info("[Stage: build_merchant_performance] input_count: %s rows", f"{input_count:,}")
    validate_schema(silver_df, {"status", "amount", "merchant_id", "merchant_name", "category", "city", "date"}, "silver input")
    
    # Filter for completed transactions
    completed_txns = silver_df.filter(col("status") == "COMPLETED")
    after_filter_count = completed_txns.count()
    logger.info("[Stage: build_merchant_performance] after_filter_count: %s rows", f"{after_filter_count:,}")
    
    # Calculate metrics
    merchant_performance_df = completed_txns.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
        .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(col("status").isin("FAILED")) / count("*") * 100).alias("failure_rate_pct")
        )
    output_count = merchant_performance_df.count()
    logger.info("[Stage: build_merchant_performance] output_count: %s rows", f"{output_count:,}")
    
    # Write the output
    merchant_performance_df.write.partitionBy("date").mode("overwrite").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read the Silver layer data
    silver_df = spark.read.parquet(silver_path)
    input_count = silver_df.count()
    logger.info("[Stage: build_customer_ltv] input_count: %s rows", f"{input_count:,}")
    validate_schema(silver_df, {"status", "amount", "customer_id", "date", "payment_method"}, "silver input")
    
    # Filter for completed transactions
    completed_txns = silver_df.filter(col("status") == "COMPLETED")
    after_filter_count = completed_txns.count()
    logger.info("[Stage: build_customer_ltv] after_filter_count: %s rows", f"{after_filter_count:,}")
    
    # Calculate metrics
    customer_ltv_df = completed_txns.groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            avg("amount").alias("avg_txn_value"),
            min("date").alias("first_txn_date"),
            max("date").alias("last_txn_date"),
            mode("payment_method").alias("preferred_payment_method")
        )
    output_count = customer_ltv_df.count()
    logger.info("[Stage: build_customer_ltv] output_count: %s rows", f"{output_count:,}")
    
    # Write the output
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read the Silver layer data
    silver_df = spark.read.parquet(silver_path)
    input_count = silver_df.count()
    logger.info("[Stage: build_daily_summary] input_count: %s rows", f"{input_count:,}")
    validate_schema(silver_df, {"status", "amount", "customer_id", "merchant_id", "date"}, "silver input")
    
    # Filter for completed transactions
    completed_txns = silver_df.filter(col("status") == "COMPLETED")
    after_filter_count = completed_txns.count()
    logger.info("[Stage: build_daily_summary] after_filter_count: %s rows", f"{after_filter_count:,}")
    
    # Calculate metrics
    daily_summary_df = completed_txns.groupBy("date") \
       .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("total_txns"),
            countDistinct("customer_id").alias("unique_customers"),
            countDistinct("merchant_id").alias("unique_merchants"),
            (count(col("status").isin("FAILED")) / count("*") * 100).alias("failure_rate_pct")
        )
    output_count = daily_summary_df.count()
    logger.info("[Stage: build_daily_summary] output_count: %s rows", f"{output_count:,}")
    
    # Write the output
    daily_summary_df.write.partitionBy("date").mode("overwrite").parquet(output_path)

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define output paths
    merchant_performance_path = f"{gold_output_dir}/merchant_performance"
    customer_ltv_path = f"{gold_output_dir}/customer_ltv"
    daily_summary_path = f"{gold_output_dir}/daily_summary"
    
    try:
        # Run each pipeline stage
        build_merchant_performance(spark, silver_path, merchant_performance_path, run_date)
        build_customer_ltv(spark, silver_path, customer_ltv_path)
        build_daily_summary(spark, silver_path, daily_summary_path, run_date)
    except Exception:
        logger.exception("Gold pipeline failed for run_date=%s", run_date)
        raise
    
    # Write run metadata
    run_metadata = {
        "run_date": run_date,
        "output_paths": {
            "merchant_performance": merchant_performance_path,
            "customer_ltv": customer_ltv_path,
            "daily_summary": daily_summary_path
        }
    }
    
    spark.sparkContext.parallelize([run_metadata]) \
        .write.mode("overwrite").json(f"{gold_output_dir}/run_metadata")

# Initialize Spark session
spark = SparkSession.builder.appName("Customer Segmentation Refresh").getOrCreate()

# Example usage
silver_path = os.environ["SIGMA_SILVER_INPUT_PATH"]
gold_output_dir = os.environ["SIGMA_GOLD_OUTPUT_DIR"]
run_date = os.environ["SIGMA_RUN_DATE"]

run_gold(spark, silver_path, gold_output_dir, run_date)
