"""
Sigma DataTech Transaction Analytics Pipeline
AI-Generated by Module 1 | Day 7 — Pipeline Brain
<<<<<<< HEAD
Generated: 2026-05-26T09:00:31.064387+00:00
=======
Generated: 2026-05-26T09:46:14.819226+00:00
>>>>>>> upstream/main

This file was produced by 1_spec_to_pipeline.py from a plain-English spec.
It is a FIRST DRAFT — review before running against production data.

Architecture: Bronze -> Silver -> Gold (medallion pattern)
"""

# ═══════════════════════════════════════════════════════════════
# SECTION 1: BRONZE + SILVER LAYERS
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
<<<<<<< HEAD
from pyspark.sql.functions import col, lit, max, broadcast, when, avg, countDistinct
from pyspark.sql.window import Window
from pyspark.sql.types import StringType, FloatType, DateType
import datetime
import logging
import os

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger("sigma_pipeline")

EXPECTED_TRANSACTION_COLUMNS = {
    "transaction_id",
    "amount",
    "status",
    "merchant_id",
    "customer_id",
    "transaction_date",
    "payment_method",
}


def validate_schema(df, expected_columns, layer_name):
    missing_columns = expected_columns - set(df.columns)
    if missing_columns:
        raise ValueError(f"{layer_name} is missing required columns: {sorted(missing_columns)}")
    logger.info("%s schema validation passed with %d columns", layer_name, len(df.columns))

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV data
    raw_df = spark.read.csv(input_path, header=True, inferSchema=False)
    input_count = raw_df.count()
    logger.info("[Stage: ingest_bronze] input_count: %s rows", f"{input_count:,}")
    validate_schema(raw_df, EXPECTED_TRANSACTION_COLUMNS, "bronze input")
    
    # Add metadata columns
    raw_df = raw_df.withColumn("ingestion_timestamp", lit(datetime.datetime.now()))
    raw_df = raw_df.withColumn("source_file", lit(input_path))
    raw_df = raw_df.withColumn("pipeline_run_id", lit(run_id))
    output_count = raw_df.count()
    logger.info("[Stage: ingest_bronze] output_count: %s rows", f"{output_count:,}")
    
    # Overwrite the run_date partition so re-running the same day is idempotent.
    raw_df.write.mode("overwrite").parquet(f"{output_path}/load_date={run_date}")

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning
    bronze_df = spark.read.parquet(f"{bronze_path}/load_date={run_date}")
    input_count = bronze_df.count()
    logger.info("[Stage: transform_silver] input_count: %s rows", f"{input_count:,}")
    validate_schema(
        bronze_df,
        EXPECTED_TRANSACTION_COLUMNS | {"ingestion_timestamp", "source_file", "pipeline_run_id"},
        "bronze partition",
    )
    
    # Cast columns to correct types
    bronze_df = bronze_df.withColumn("amount", col("amount").cast(FloatType()))
    bronze_df = bronze_df.withColumn("transaction_date", col("transaction_date").cast(DateType()))
    bronze_df = bronze_df.withColumn("customer_id", col("customer_id").cast(StringType()))
    bronze_df = bronze_df.withColumn("merchant_id", col("merchant_id").cast(StringType()))
    
    # Filter NULL transaction_id and negative amounts
    bronze_df = bronze_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))
    after_filter_count = bronze_df.count()
    logger.info("[Stage: transform_silver] after_filter_count: %s rows", f"{after_filter_count:,}")
    
    # Deduplicate on transaction_id keeping latest ingestion_timestamp
    window = Window.partitionBy("transaction_id")
    bronze_df = bronze_df.withColumn("rank",
                                    when(col("ingestion_timestamp") ==
                                         max("ingestion_timestamp").over(window), 1).otherwise(0))
    bronze_df = bronze_df.filter(col("rank") == 1).drop("rank")
    after_dedup_count = bronze_df.count()
    logger.info("[Stage: transform_silver] after_dedup_count: %s rows", f"{after_dedup_count:,}")
    
    # Read merchants data and broadcast hint, cache merchants
    merchants_df = spark.read.parquet(merchants_path)
    merchants_df = broadcast(merchants_df)
    merchants_df.cache()
    
    # Join with merchants
    joined_df = bronze_df.join(merchants_df, bronze_df.merchant_id == merchants_df.merchant_id, "left")
    
    # Add quality_flag column
    joined_df = joined_df.withColumn("quality_flag", 
                                     when(col("merchant_id").isNotNull(), "CLEAN").otherwise("UNMATCHED"))
    output_count = joined_df.count()
    logger.info("[Stage: transform_silver] output_count: %s rows", f"{output_count:,}")
    
    # Write to Silver layer partitioned by date
    joined_df.write.mode("overwrite").parquet(f"{output_path}/load_date={run_date}")

def main():
    # Initialize Spark session
    spark = SparkSession.builder.appName("Customer Segmentation Pipeline").getOrCreate()
    
    # Define paths and run details
    input_path = os.environ["SIGMA_TRANSACTIONS_RAW_PATH"]
    output_bronze_path = os.environ["SIGMA_BRONZE_OUTPUT_PATH"]
    output_silver_path = os.environ["SIGMA_SILVER_OUTPUT_PATH"]
    merchants_path = os.environ["SIGMA_MERCHANTS_DIM_PATH"]
    run_date = datetime.datetime.now().strftime("%Y%m%d")
    run_id = "run_id_12345"
    
    try:
        # Ingest Bronze layer
        ingest_bronze(spark, input_path, output_bronze_path, run_date, run_id)

        # Transform Silver layer
        transform_silver(spark, output_bronze_path, merchants_path, output_silver_path, run_date)
    except Exception:
        logger.exception("Pipeline failed for run_date=%s run_id=%s", run_date, run_id)
        raise
=======
from pyspark.sql.functions import col, lit, coalesce, max as max_
from pyspark.sql.types import StringType, FloatType, DateType
import json
import os

def ingest_bronze(spark, input_path, output_path, run_date, run_id):
    # Read raw CSV files with all columns as strings
    transactions_df = (spark.read.option("header", "true")
                      .option("inferSchema", "false")
                       .csv(input_path))
    
    # Add metadata columns
    transactions_df = (transactions_df.withColumn("ingestion_timestamp", lit(run_date))
                      .withColumn("source_file", lit("transactions.csv"))
                       .withColumn("pipeline_run_id", lit(run_id)))
    
    # Write as Parquet partitioned by date
    transactions_df.write.partitionBy("ingestion_timestamp").parquet(output_path)

def transform_silver(spark, bronze_path, merchants_path, output_path, run_date):
    # Read Bronze Parquet with partition pruning on run_date
    transactions_df = (spark.read.parquet(bronze_path)
                      .where(col("ingestion_timestamp") == run_date))
    
    # Cast columns to correct types
    transactions_df = (transactions_df.withColumn("amount", col("amount").cast(FloatType()))
                       .withColumn("transaction_date", col("transaction_date").cast(DateType())))
    
    # Filter NULL transaction_id and negative amounts
    transactions_df = transactions_df.filter((col("transaction_id").isNotNull()) & (col("amount") >= 0))
    
    # Deduplicate on transaction_id keeping latest ingestion_timestamp
    deduped_df = (transactions_df.groupBy("transaction_id")
                 .agg(max_("ingestion_timestamp").alias("latest_timestamp")))
    transactions_df = transactions_df.join(deduped_df, on=["transaction_id", "ingestion_timestamp"], how="left_semi")
    
    # Read merchants data and cache it
    merchants_df = (spark.read.option("header", "true")
                   .option("inferSchema", "false")
                   .csv(merchants_path)
                   .withColumn("merchant_id", col("merchant_id").cast(StringType())))
    merchants_df = merchants_df.cache()
    
    # Join transactions with merchants
    enriched_df = (transactions_df.join(merchants_df, on="merchant_id", how="left")
                  .withColumn("quality_flag", coalesce(col("merchant_name"), lit("UNMATCHED"))))
    
    # Write as Parquet partitioned by date
    enriched_df.write.partitionBy("transaction_date").parquet(output_path)

def main():
    # Initialize Spark session
    spark = (SparkSession.builder
            .appName("Sigma DataTech Transaction Analytics Pipeline")
             .getOrCreate())
    
    # Define paths and run metadata
    input_path = "s3://sigma-datatech/bronze/transactions.csv"
    bronze_path = "s3://sigma-datatech/silver/transactions"
    merchants_path = "s3://sigma-datatech/bronze/merchants.csv"
    output_path = "s3://sigma-datatech/silver/transactions"
    run_date = "2026-05-27"
    run_id = "run_id_20260527"
    
    # Ingest Bronze layer
    ingest_bronze(spark, input_path, bronze_path, run_date, run_id)
    
    # Transform to Silver layer
    transform_silver(spark, bronze_path, merchants_path, output_path, run_date)
    
    # Write run metadata summary to a JSON file
    metadata = {"run_date": run_date, "run_id": run_id, "status": "COMPLETED"}
    with open(f"s3://sigma-datatech/metadata/run_metadata_{run_date}.json", "w") as f:
        json.dump(metadata, f)
>>>>>>> upstream/main

if __name__ == "__main__":
    main()


# ═══════════════════════════════════════════════════════════════
# SECTION 2: GOLD AGGREGATION LAYER
# ═══════════════════════════════════════════════════════════════
from pyspark.sql import SparkSession
<<<<<<< HEAD
from pyspark.sql.functions import col, sum, count, max, min, mode, expr, to_date
from pyspark.sql.types import StructType, StructField, StringType, IntegerType, DoubleType, DateType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read the Silver layer data
    silver_df = spark.read.parquet(silver_path)
    input_count = silver_df.count()
    logger.info("[Stage: build_merchant_performance] input_count: %s rows", f"{input_count:,}")
    validate_schema(silver_df, {"status", "amount", "merchant_id", "merchant_name", "category", "city", "date"}, "silver input")
    
    # Filter for completed transactions
    completed_txns = silver_df.filter(col("status") == "COMPLETED")
    after_filter_count = completed_txns.count()
    logger.info("[Stage: build_merchant_performance] after_filter_count: %s rows", f"{after_filter_count:,}")
    
    # Calculate metrics
    merchant_performance_df = completed_txns.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
        .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("txn_count"),
            (count(col("status").isin("FAILED")) / count("*") * 100).alias("failure_rate_pct")
        )
    output_count = merchant_performance_df.count()
    logger.info("[Stage: build_merchant_performance] output_count: %s rows", f"{output_count:,}")
    
    # Write the output
    merchant_performance_df.write.partitionBy("date").mode("overwrite").parquet(output_path)

def build_customer_ltv(spark, silver_path, output_path):
    # Read the Silver layer data
    silver_df = spark.read.parquet(silver_path)
    input_count = silver_df.count()
    logger.info("[Stage: build_customer_ltv] input_count: %s rows", f"{input_count:,}")
    validate_schema(silver_df, {"status", "amount", "customer_id", "date", "payment_method"}, "silver input")
    
    # Filter for completed transactions
    completed_txns = silver_df.filter(col("status") == "COMPLETED")
    after_filter_count = completed_txns.count()
    logger.info("[Stage: build_customer_ltv] after_filter_count: %s rows", f"{after_filter_count:,}")
    
    # Calculate metrics
    customer_ltv_df = completed_txns.groupBy("customer_id") \
       .agg(
            sum("amount").alias("total_spent"),
            count("*").alias("total_txns"),
            avg("amount").alias("avg_txn_value"),
            min("date").alias("first_txn_date"),
            max("date").alias("last_txn_date"),
            mode("payment_method").alias("preferred_payment_method")
        )
    output_count = customer_ltv_df.count()
    logger.info("[Stage: build_customer_ltv] output_count: %s rows", f"{output_count:,}")
    
    # Write the output
    customer_ltv_df.write.mode("overwrite").parquet(output_path)

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read the Silver layer data
    silver_df = spark.read.parquet(silver_path)
    input_count = silver_df.count()
    logger.info("[Stage: build_daily_summary] input_count: %s rows", f"{input_count:,}")
    validate_schema(silver_df, {"status", "amount", "customer_id", "merchant_id", "date"}, "silver input")
    
    # Filter for completed transactions
    completed_txns = silver_df.filter(col("status") == "COMPLETED")
    after_filter_count = completed_txns.count()
    logger.info("[Stage: build_daily_summary] after_filter_count: %s rows", f"{after_filter_count:,}")
    
    # Calculate metrics
    daily_summary_df = completed_txns.groupBy("date") \
       .agg(
            sum("amount").alias("total_revenue"),
            count("*").alias("total_txns"),
            countDistinct("customer_id").alias("unique_customers"),
            countDistinct("merchant_id").alias("unique_merchants"),
            (count(col("status").isin("FAILED")) / count("*") * 100).alias("failure_rate_pct")
        )
    output_count = daily_summary_df.count()
    logger.info("[Stage: build_daily_summary] output_count: %s rows", f"{output_count:,}")
    
    # Write the output
    daily_summary_df.write.partitionBy("date").mode("overwrite").parquet(output_path)

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define output paths
    merchant_performance_path = f"{gold_output_dir}/merchant_performance"
    customer_ltv_path = f"{gold_output_dir}/customer_ltv"
    daily_summary_path = f"{gold_output_dir}/daily_summary"
    
    try:
        # Run each pipeline stage
        build_merchant_performance(spark, silver_path, merchant_performance_path, run_date)
        build_customer_ltv(spark, silver_path, customer_ltv_path)
        build_daily_summary(spark, silver_path, daily_summary_path, run_date)
    except Exception:
        logger.exception("Gold pipeline failed for run_date=%s", run_date)
        raise
    
    # Write run metadata
    run_metadata = {
        "run_date": run_date,
        "output_paths": {
            "merchant_performance": merchant_performance_path,
            "customer_ltv": customer_ltv_path,
            "daily_summary": daily_summary_path
        }
    }
    
    spark.sparkContext.parallelize([run_metadata]) \
        .write.mode("overwrite").json(f"{gold_output_dir}/run_metadata")

# Initialize Spark session
spark = SparkSession.builder.appName("Customer Segmentation Refresh").getOrCreate()

# Example usage
silver_path = os.environ["SIGMA_SILVER_INPUT_PATH"]
gold_output_dir = os.environ["SIGMA_GOLD_OUTPUT_DIR"]
run_date = os.environ["SIGMA_RUN_DATE"]

run_gold(spark, silver_path, gold_output_dir, run_date)
=======
from pyspark.sql.functions import col, sum, count, max, broadcast, when, avg, first, last, mode
from pyspark.sql.types import StructType, StructField, StringType, FloatType, DateType

def build_merchant_performance(spark, silver_path, output_path, run_date):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Filter for completed transactions
    completed_df = silver_df.filter(col("status") == "COMPLETED")
    
    # Calculate total revenue and transaction count per merchant
    revenue_df = completed_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(sum("amount").alias("total_revenue"), count("*").alias("txn_count"))
    
    # Calculate failure rate per merchant
    all_txns_df = silver_df.groupBy("merchant_id", "merchant_name", "category", "city", "date") \
       .agg(count("*").alias("total_txns"), count(when(col("status") == "FAILED", 1)).alias("failed_txns"))
    
    failure_rate_df = all_txns_df.withColumn("failure_rate_pct", (col("failed_txns") / col("total_txns") * 100).cast(FloatType()))
    
    # Join revenue and failure rate calculations
    merchant_performance_df = revenue_df.join(failure_rate_df, ["merchant_id", "merchant_name", "category", "city", "date"], "left") \
        .select("merchant_id", "merchant_name", "category", "city", "date", "total_revenue", "txn_count", "failure_rate_pct")
    
    # Write output to Gold layer
    merchant_performance_df.write.partitionBy("date").mode("overwrite").parquet(output_path + "/merchant_performance")

def build_customer_ltv(spark, silver_path, output_path):
    # Read Silver layer data
    silver_df = spark.read.parquet(silver_path)
    
    # Filter for completed transactions
    completed_df = silver_df.filter(col("status") == "COMPLETED")
    
    # Calculate total spent, total transactions, and preferred payment method per customer
    ltv_df = completed_df.groupBy("customer_id") \
       .agg(sum("amount").alias("total_spent"), count("*").alias("total_txns"), avg("amount").alias("avg_txn_value"), 
             first("transaction_date").alias("first_txn_date"), last("transaction_date").alias("last_txn_date"), 
             mode("payment_method").alias("preferred_payment_method"))
    
    # Write output to Gold layer
    ltv_df.write.mode("overwrite").parquet(output_path + "/customer_ltv")

def build_daily_summary(spark, silver_path, output_path, run_date):
    # Read Silver layer data for the specific date
    silver_df = spark.read.parquet(silver_path).filter(col("date") == run_date)
    
    # Calculate total revenue, total transactions, unique customers, and unique merchants
    total_revenue_df = silver_df.filter(col("status") == "COMPLETED") \
        .groupBy("date").agg(sum("amount").alias("total_revenue"), count("*").alias("total_txns"))
    
    unique_customers_df = silver_df.groupBy("date").agg(countDistinct("customer_id").alias("unique_customers"))
    
    unique_merchants_df = silver_df.groupBy("date").agg(countDistinct("merchant_id").alias("unique_merchants"))
    
    # Calculate failure rate
    all_txns_df = silver_df.groupBy("date").agg(count("*").alias("total_txns"), count(when(col("status") == "FAILED", 1)).alias("failed_txns"))
    
    failure_rate_df = all_txns_df.withColumn("failure_rate_pct", (col("failed_txns") / col("total_txns") * 100).cast(FloatType()))
    
    # Join all calculations
    daily_summary_df = total_revenue_df.join(unique_customers_df, "date", "inner") \
       .join(unique_merchants_df, "date", "inner") \
       .join(failure_rate_df, "date", "left") \
       .select("date", "total_revenue", "total_txns", "unique_customers", "unique_merchants", "failure_rate_pct")
    
    # Write output to Gold layer
    daily_summary_df.write.partitionBy("date").mode("overwrite").parquet(output_path + "/daily_summary")

def run_gold(spark, silver_path, gold_output_dir, run_date):
    # Define run metadata
    run_metadata = {"run_date": run_date, "silver_path": silver_path, "gold_output_dir": gold_output_dir}
    
    # Build Gold layer tables
    build_merchant_performance(spark, silver_path, f"{gold_output_dir}/merchant_performance", run_date)
    build_customer_ltv(spark, silver_path, f"{gold_output_dir}/customer_ltv")
    build_daily_summary(spark, silver_path, f"{gold_output_dir}/daily_summary", run_date)
    
    # Write run metadata to JSON
    spark.sparkContext.parallelize([run_metadata]).write.json(f"{gold_output_dir}/run_metadata")

# Initialize Spark Session
spark = SparkSession.builder.appName("Sigma DataTech Transaction Analytics Pipeline").getOrCreate()
>>>>>>> upstream/main
